#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Bootstrap;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Bootstrap.Extensions;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Objects;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Text;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Bootstrap4Alert.cshtml")]
    public partial class _Views_Shared__Bootstrap4Alert_cshtml : System.Web.Mvc.WebViewPage<Bootstrap4.Alert>
    {
        public _Views_Shared__Bootstrap4Alert_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 10 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 201), Tuple.Create("\"", 354)
, Tuple.Create(Tuple.Create("", 209), Tuple.Create("alert", 209), true)
            
            #line 11 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create(" ", 214), Tuple.Create<System.Object, System.Int32>(Model.AlertType.ToCssClass() + (Model.Closeable ? " alert-dismissible" : "") + (Model.Fade ? " fade" : "") + (Model.Show ? " show" : "")
            
            #line default
            #line hidden
, 215), false)
);

WriteLiteral(">\r\n");

            
            #line 12 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
        
            
            #line default
            #line hidden
            
            #line 12 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
          
            if (Model.Closeable)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"close\"");

WriteLiteral(">&times;</button>\r\n");

            
            #line 16 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
            }

            if (Model.Emphasis != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <strong>");

            
            #line 20 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                   Write(Model.Emphasis);

            
            #line default
            #line hidden
WriteLiteral("</strong>");

            
            #line 20 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                            Write(" - ");

            
            #line default
            #line hidden
            
            #line 20 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                        
            }

            var message = TextUtil.RevealNullOrBlank(Zap.String(Model.Message));
            if (Model.EncodeHtml)
            {
                
            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
           Write(message);

            
            #line default
            #line hidden
            
            #line 26 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                        
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
           Write(Html.Raw(message.Replace("\r\n", "<br />").Replace("\n", "<br />")));

            
            #line default
            #line hidden
            
            #line 30 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                                                    
            }

            if (Model.MessageDetails != null)
            {
                if (Model.IsMessageDetailsHidden)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 38 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                   Write(Html.Raw(Model.MessageDetails));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 40 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                }
                else
                {
                    var alertDetailsElementID = "alert-details-" + Guid.NewGuid();

            
            #line default
            #line hidden
WriteLiteral("                    <div>\r\n                        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1469), Tuple.Create("\"", 1540)
, Tuple.Create(Tuple.Create("", 1479), Tuple.Create("Bootstrap4.toggleAlertDetails(this,", 1479), true)
, Tuple.Create(Tuple.Create(" ", 1514), Tuple.Create("\'", 1515), true)
            
            #line 45 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
             , Tuple.Create(Tuple.Create("", 1516), Tuple.Create<System.Object, System.Int32>(alertDetailsElementID
            
            #line default
            #line hidden
, 1516), false)
, Tuple.Create(Tuple.Create("", 1538), Tuple.Create("\')", 1538), true)
);

WriteLiteral(">show details</a>\r\n                    </div>\r\n");

            
            #line 47 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"

                    var preStyles = Model.IsMessageDetailsPreFormatted ? "font-family:Consolas,monospace;font-size:.8em;white-space:pre;" : "";

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1759), Tuple.Create("\"", 1786)
            
            #line 49 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create("", 1764), Tuple.Create<System.Object, System.Int32>(alertDetailsElementID
            
            #line default
            #line hidden
, 1764), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1787), Tuple.Create("\"", 1818)
, Tuple.Create(Tuple.Create("", 1795), Tuple.Create("display:none;", 1795), true)
            
            #line 49 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create("", 1808), Tuple.Create<System.Object, System.Int32>(preStyles
            
            #line default
            #line hidden
, 1808), false)
);

WriteLiteral(">\r\n");

            
            #line 50 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                        
            
            #line default
            #line hidden
            
            #line 50 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                         if (Model.IsMessageDetailsEncodeHtml)
                        {
                            
            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                       Write(Model.MessageDetails);

            
            #line default
            #line hidden
            
            #line 52 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                 
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                       Write(Html.Raw(Model.MessageDetails));

            
            #line default
            #line hidden
            
            #line 56 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                           
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");

            
            #line 59 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                }
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 63 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 65 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
 if (Model.MessageDetails != null && !Model.IsMessageDetailsHidden)
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        Bootstrap4 = {
            toggleAlertDetails: function (clickedLink, alertDetailsElementID) {
                if (window.jQuery) {
                    var $clickedLink = $(clickedLink);
                    if ($clickedLink.prop(""toggled"")) {
                        $(""#"" + alertDetailsElementID).hide();
                        $clickedLink.text(""show details"");
                        $clickedLink.prop(""toggled"", false);
                    }
                    else {
                        $(""#"" + alertDetailsElementID).show();
                        $clickedLink.text(""hide details"");
                        $clickedLink.prop(""toggled"", true);
                    }
                }
                else {
                    if (clickedLink.toggled) {
                        document.getElementById(alertDetailsElementID).style.display = ""none"";
                        clickedLink.innerText = ""show details"";
                        clickedLink.toggled = false;
                    }
                    else {
                        document.getElementById(alertDetailsElementID).style.display = ""block"";
                        clickedLink.innerText = ""hide details"";
                        clickedLink.toggled = true;
                    }
                }
            }
        }
    </script>
");

            
            #line 98 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
