#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    
    #line 3 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Bootstrap;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
    using Horseshoe.NET.Text;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Views/Shared/_Bootstrap4Alert.cshtml")]
    public partial class _Views_Shared__Bootstrap4Alert_cshtml : System.Web.Mvc.WebViewPage<Bootstrap4.Alert>
    {
        public _Views_Shared__Bootstrap4Alert_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

WriteLiteral("\r\n");

            
            #line 8 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
  

            
            #line default
            #line hidden
WriteLiteral("    <div");

WriteAttribute("class", Tuple.Create(" class=\"", 128), Tuple.Create("\"", 281)
, Tuple.Create(Tuple.Create("", 136), Tuple.Create("alert", 136), true)
            
            #line 9 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create(" ", 141), Tuple.Create<System.Object, System.Int32>(Model.AlertType.ToCssClass() + (Model.Closeable ? " alert-dismissible" : "") + (Model.Fade ? " fade" : "") + (Model.Show ? " show" : "")
            
            #line default
            #line hidden
, 142), false)
);

WriteLiteral(">\r\n");

            
            #line 10 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
        
            
            #line default
            #line hidden
            
            #line 10 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
          
            if (Model.Closeable)
            {

            
            #line default
            #line hidden
WriteLiteral("                <button");

WriteLiteral(" type=\"button\"");

WriteLiteral(" class=\"close\"");

WriteLiteral(" data-dismiss=\"alert\"");

WriteLiteral(" aria-label=\"close\"");

WriteLiteral(">&times;</button>\r\n");

            
            #line 14 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
            }

            if (Model.Emphasis != null)
            {

            
            #line default
            #line hidden
WriteLiteral("                <strong>");

            
            #line 18 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                   Write(Model.Emphasis);

            
            #line default
            #line hidden
WriteLiteral("</strong>");

            
            #line 18 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                
            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                            Write(" - ");

            
            #line default
            #line hidden
            
            #line 18 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                        
            }

            var message = TextUtil.RevealNullOrBlank(TextUtil.Zap(Model.Message));
            if (Model.EncodeHtml)
            {
                
            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
           Write(message);

            
            #line default
            #line hidden
            
            #line 24 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                        
            }
            else
            {
                
            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
           Write(Html.Raw(message.Replace("\r\n", "<br />").Replace("\n", "<br />")));

            
            #line default
            #line hidden
            
            #line 28 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                                                    
            }

            if (Model.MessageDetails != null)
            {
                if (Model.IsMessageDetailsHidden)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteLiteral(" style=\"display:none;\"");

WriteLiteral(">\r\n");

WriteLiteral("                        ");

            
            #line 36 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                   Write(Html.Raw(Model.MessageDetails));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");

            
            #line 38 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                }
                else
                {
                    var alertDetailsElementID = "alert-details-" + Guid.NewGuid();

            
            #line default
            #line hidden
WriteLiteral("                    <div>\r\n                        <a");

WriteLiteral(" href=\"javascript:;\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 1398), Tuple.Create("\"", 1469)
, Tuple.Create(Tuple.Create("", 1408), Tuple.Create("Bootstrap4.toggleAlertDetails(this,", 1408), true)
, Tuple.Create(Tuple.Create(" ", 1443), Tuple.Create("\'", 1444), true)
            
            #line 43 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
             , Tuple.Create(Tuple.Create("", 1445), Tuple.Create<System.Object, System.Int32>(alertDetailsElementID
            
            #line default
            #line hidden
, 1445), false)
, Tuple.Create(Tuple.Create("", 1467), Tuple.Create("\')", 1467), true)
);

WriteLiteral(">show details</a>\r\n                    </div>\r\n");

            
            #line 45 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"

                    var preStyles = Model.IsMessageDetailsPreFormatted ? "font-family:Consolas,monospace;font-size:.8em;white-space:pre;" : "";

            
            #line default
            #line hidden
WriteLiteral("                    <div");

WriteAttribute("id", Tuple.Create(" id=\"", 1688), Tuple.Create("\"", 1715)
            
            #line 47 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create("", 1693), Tuple.Create<System.Object, System.Int32>(alertDetailsElementID
            
            #line default
            #line hidden
, 1693), false)
);

WriteAttribute("style", Tuple.Create(" style=\"", 1716), Tuple.Create("\"", 1747)
, Tuple.Create(Tuple.Create("", 1724), Tuple.Create("display:none;", 1724), true)
            
            #line 47 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
, Tuple.Create(Tuple.Create("", 1737), Tuple.Create<System.Object, System.Int32>(preStyles
            
            #line default
            #line hidden
, 1737), false)
);

WriteLiteral(">");

            
            #line 47 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                                                      if (Model.IsMessageDetailsEncodeHtml)
                        {
                            
            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                       Write(Model.MessageDetails);

            
            #line default
            #line hidden
            
            #line 49 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                 
                        }
                        else
                        {
                            
            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                       Write(Html.Raw(Model.MessageDetails));

            
            #line default
            #line hidden
            
            #line 53 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                                                           
                        }
            
            #line default
            #line hidden
WriteLiteral("</div>\r\n");

            
            #line 55 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
                }
            }
        
            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n");

            
            #line 59 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

            
            #line 61 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
 if (Model.MessageDetails != null && !Model.IsMessageDetailsHidden)
{

            
            #line default
            #line hidden
WriteLiteral("    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        Bootstrap4 = {
            toggleAlertDetails: function (clickedLink, alertDetailsElementID) {
                if (window.jQuery) {
                    var $clickedLink = $(clickedLink);
                    if ($clickedLink.prop(""toggled"")) {
                        $(""#"" + alertDetailsElementID).hide();
                        $clickedLink.text(""show details"");
                        $clickedLink.prop(""toggled"", false);
                    }
                    else {
                        $(""#"" + alertDetailsElementID).show();
                        $clickedLink.text(""hide details"");
                        $clickedLink.prop(""toggled"", true);
                    }
                }
                else {
                    if (clickedLink.toggled) {
                        document.getElementById(alertDetailsElementID).style.display = ""none"";
                        clickedLink.innerText = ""show details"";
                        clickedLink.toggled = false;
                    }
                    else {
                        document.getElementById(alertDetailsElementID).style.display = ""block"";
                        clickedLink.innerText = ""hide details"";
                        clickedLink.toggled = true;
                    }
                }
            }
        }
    </script>
");

            
            #line 94 "..\..\Views\Shared\_Bootstrap4Alert.cshtml"
}

            
            #line default
            #line hidden
        }
    }
}
#pragma warning restore 1591
